jobs:
  - job: bundle_and_upload_appium_zip
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      NODE_ENV: production
      CC: gcc
      CXX: g++
    steps:
    - script: gcc --version
      displayName: Print GCC Version
    - script: brew upgrade carthage
      displayName: Upgrade Carthage
    - task: NodeTool@0
      inputs:
        versionSpec: '11.x'
    - script: npm install (production only)
      displayName: npm install
    - script: |
        npm install gulp
        npm install appium-gulp-plugins
      displayName: npm install gulp and appium-gulp-plugins
    - script: |
        pushd node_modules/appium-xcuitest-driver/WebDriverAgent
        carthage bootstrap --no-use-binaries
        cp Cartfile.resolved Carthage
        mkdir -p ./Resources/WebDriverAgent.bundle
        popd
      displayName: Fully build XCUITestDriver
    - script: npm run build
      displayName: npm run build
    - script: npm prune
      displayName: Prune Dev Dependencies
    - script: npm run zip
      displayName: npm run zip
    - script: |
        npm install gulp
        npm install appium-gulp-plugins
      displayName: npm install gulp and appium-gulp-plugins (again)
    - script: npm run upload
      displayName: Upload to appium/appium-build-store
    - script: npx gulp sauce-storage-upload
      displayName: Upload to Sauce Storage
